theme: jekyll-theme-cayman

# Site settings
title: wml的博客呀
SEOTitle: wuml的博客 | my Blog
header-img: img/home-bg.jpg
email: 1054527951@qq.com
description: "wumeilian | 未知的世界才值得期待"
keyword: "wumeilian, wml"
url: "https://wumeilian.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'


# avatar and Favicon
# avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: favicon.ico
